#pragma once

#include "Patches.h"

/* Base configuration */
#define ALLOWED_WILDCARD_DOMAINS "rbxcdn.com", "roblox.com"
#define ALLOWED_DOMAINS
#define ALLOWED_SCHEMES "http", "https"
#define ALLOWED_EMBEDDED_SCHEMES "javascript", "jscript", "res"
#define PUBLIC_KEY ""

/* Addresses and padding sizes */

#define ADDRESS_CONTEXT__ISINROLE                  LOCATION(0x0)
#define ADDRESS_CONTEXT__REQUIREPERMISSION         LOCATION(0x0)
#define ADDRESS_CRYPT__VERIFYSIGNATUREBASE64       LOCATION(0x0)
#define ADDRESS_GAME__CONSTRUCT                    LOCATION(0x0)
#define ADDRESS_HTTP__HTTPGETPOSTWININET           LOCATION(0x0)
#define ADDRESS_HTTP__TRUSTCHECK                   LOCATION(0x0)
#define ADDRESS_SERVERREPLICATOR__PROCESSTICKET    LOCATION(0x0)
#define ADDRESS_SERVERREPLICATOR__SENDTOP          LOCATION(0x0)
#define ADDRESS_STANDARDOUT__PRINT                 LOCATION(0x0)

#define CLASSLOCATION_CAPP                         LOCATION(0x0)
#define CLASSLOCATION_CROBLOXAPP                   LOCATION(0x0)

#define CLASSPADDING_CROBLOXDOC__WORKSPACE         1

#define ADDRESS_CAPP__CREATEGAME                   LOCATION(0x0)
#define ADDRESS_CAPP__ROBLOXAUTHENTICATE           LOCATION(0x0)
#define ADDRESS_CCOMMANDLINEINFO__PARSELAST        LOCATION(0x0)
#define ADDRESS_CROBLOXAPP__CREATEDOCUMENT         LOCATION(0x0)
#define ADDRESS_CROBLOXAPP__INITINSTANCE           LOCATION(0x0)
#define ADDRESS_CROBLOXCOMMANDLINEINFO__PARSEPARAM LOCATION(0x0)
#define ADDRESS_CWORKSPACE__EXECURLSCRIPT          LOCATION(0x0)